/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.43.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as businesses from "../businesses.js";
import type * as categories from "../categories.js";
import type * as crons from "../crons.js";
import type * as employees from "../employees.js";
import type * as inventory from "../inventory.js";
import type * as locations from "../locations.js";
import type * as platform_maintenance from "../platform/maintenance.js";
import type * as onboarding from "../onboarding.js";
import type * as products from "../products.js";
import type * as platform_seed from "../platform/seed.js";
import type * as suppliers from "../suppliers.js";
import type * as taxRates from "../taxRates.js";
import type * as users from "../users.js";

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  businesses: typeof businesses;
  categories: typeof categories;
  crons: typeof crons;
  employees: typeof employees;
  inventory: typeof inventory;
  locations: typeof locations;
  "platform/maintenance": typeof platform_maintenance;
  onboarding: typeof onboarding;
  products: typeof products;
  "platform/seed": typeof platform_seed;
  suppliers: typeof suppliers;
  taxRates: typeof taxRates;
  users: typeof users;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
